---
title: "Untitled"
output: html_document
date: '2024-03-14'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("../sim/utilities.R")
library(sgdGMF)
library(dplyr)
library(bluster)
library(ggplot2)
library(viridis)
library("patchwork")


sim_full <- readRDS(file = "Data/BE1/final/sce.RDS")
celltypes <- colData(sim_full)$celltype

rm(sim_full)

df <- data.frame("T1" = NULL,"T2" = NULL, "dim" = NULL, "hvg" = NULL, "celltypes" = NULL)
for (i in c(100,200,500,1000,1500,2000)){
  if(i == 500){
    sgd_model <- readRDS(file = paste0("Output_models/sgdGMF-B-SGD-fit-list.RDS"))

  }else{
  sgd_model <- readRDS(file = paste0("Output_models/sgdGMF-B-SGD-fit-list-",i,"-hvg.RDS"))
  }
  
  for(j in c(5,10,13)){
    set.seed(100)
    tsne <- scale(Rtsne::Rtsne(sgd_model[[j]]$U, dims = 2, 
                                 verbose = TRUE, num_threads = 8)$Y)
    df <- rbind(df, data.frame(tsne[,1], 
                              tsne[,2],
                              rep(j, nrow(sgd_model[[j]]$U)), 
                              rep(i, nrow(sgd_model[[j]]$U)), 
                              celltypes))
  }
}
colnames(df) <- c("T1", "T2", "dim", "hvg", "celltypes")
df$dim[df$dim == 13] <- 30
df$dim <- as.factor(df$dim)
df$hvg <- as.factor(df$hvg)
df$celltypes <- as.factor(df$celltypes)
#saveRDS(df, file = "tsneplotdf.RDS")
df <- readRDS(file = "~/sgdGMF_Paper/Benchmarking/Arigoni_copy/tsneplotdf.RDS")

```


```{r}
dim.labs <- c("Latent dimensions: 5", "Latent dimensions: 10", "Latent dimensions: 30")
names(dim.labs) <- c("5", "10", "30")

hvg.labs <- c("High variable \n genes: 100", "High variable \n genes: 200",
              "High variable \n genes: 500", "High variable \n genes: 1000",
              "High variable \n genes: 1500", "High variable \n genes: 2000")
names(hvg.labs) <- c("100", "200","500", "1000","1500", "2000")
# Use the custom labeller in your plot



# Use the custom labeller in your plot
p1 <- ggplot(df, aes(x  = T1, y = T2, col = celltypes)) +
  geom_point(alpha = 0.5, size = 1) + 
  facet_grid(hvg ~ dim, labeller = labeller(hvg = hvg.labs, dim = dim.labs)) +
  theme_bw() + 
  theme(legend.position = "none", 
        axis.title = element_blank(),
        strip.text.y = element_text(angle = 0),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill = "lightgrey"))



filepath = "~/sgdGMF_Paper/Benchmarking/Arigoni/Output_models"
filename = "hvg_comparison.pdf"
zoom = 2
width = 5.5
height = 4
ggsave(filename = filename, path = filepath, plot = p1,
       width = zoom  * width, height = zoom * height)



```


```{r}
source("../sim/utilities.R")
library(dplyr)
library(bluster)
library(ggplot2)
library(viridis)
library("patchwork")


sim_full <- readRDS(file = "Data/BE1/final/sce.RDS")
celltypes <- colData(sim_full)$celltype

rm(sim_full)

set.seed(100)
dimensions <- c(1:10, 15, 20, 30, 40, 50)

df <- data.frame("celltype" = NULL,"dim" = NULL, "mean" = NULL, "hvg" = NULL)
for (i in c(100,200,500,1000,1500,2000)){
  if(i == 500){
    sgd_model <- readRDS(file = paste0("Output_models/sgdGMF-B-SGD-fit-list.RDS"))

  }else{
  sgd_model <- readRDS(file = paste0("Output_models/sgdGMF-B-SGD-fit-list-",i,"-hvg.RDS"))
  }
  


    purity_rescaled <- lapply(1:15, function(x) {
      U_rescaled <- prcomp(sgd_model[[x]]$U %*% t(sgd_model[[x]]$V))$x
      pur <- neighborPurity(U_rescaled, clusters = celltypes)
      pur$dim <- c(dimensions[x])
      return(pur)
      })
    purity_rescaled_merged <- do.call(rbind, purity_rescaled)
    purity_rescaled_merged$dim <- as.factor(purity_rescaled_merged$dim)
    purity_rescaled_mean <- as.data.frame(purity_rescaled_merged) %>% group_by(maximum, dim) %>%
      summarise(mean = mean(purity))
    
    df <- rbind(df, data.frame(purity_rescaled_mean$maximum, 
                              purity_rescaled_mean$dim,
                              purity_rescaled_mean$mean, 
                              rep(i, nrow(purity_rescaled_mean))))
  
}
colnames(df) <- c("celltype", "dim", "mean", "hvg")
df$dim <- as.factor(df$dim)
df$hvg <- as.factor(df$hvg)
df$celltype <- as.factor(df$celltype)
```


```{r}
df <- readRDS(file = "~/sgdGMF_Paper/Benchmarking/Arigoni_copy/purity_hvg_LF_plot.RDS")
#saveRDS(df, file = "purity_hvg_LF_plot.RDS")
df
```
```{r}
labels_purity <- c("Mean cell-line purity")
names(labels_purity) <- "1"

plt_purity <- df %>%
  ggplot(map = aes(x = dim, y = mean, col = (hvg))) +
  geom_point() +
  geom_line(map = aes(x = as.numeric(dim))) +
  #geom_vline(xintercept = c("9", "15"), lty = 2, col = "gray40") +
  geom_point() +
  facet_wrap(~celltype, scale = "free_y", nrow = 2) +
  labs(x = "Latent space rank", col = "Celltype") +
  theme_bw() +
  ylab("Mean cell-line purity")+
  theme(legend.position = "bottom",
        legend.text = element_text(size = 10),
        plot.margin = margin(0.3, 0.2, 0.2, 0.3, "cm"),
        strip.text = element_text(size = 11))
```

```{r}
filepath = "~/sgdGMF_Paper/Benchmarking/Arigoni/Output_models"
filename = "hvg_comparison_purity.pdf"
zoom = 2
width = 5.5
height = 4
ggsave(filename = filename, path = filepath, plot = plt_purity,
       width = zoom  * width, height = zoom * height)

```

