---
title: "Model selection and hvg influence"
output: html_document
date: '2024-03-10'
---

```{r}
source("../sim/utilities.R")
library(sgdGMF)
library(dplyr)
library(scran)

sim_full <- readRDS(file = "Data/BE1/final/sce.RDS")
ncores <- 8

```

```{r}
set.seed(100)

## LOAD DATA ----
rowData(sim_full)$biological.var <- NULL
sim <- sim_full[,colData(sim_full)$celltype %in% c("A549", "CCL-185-IG")]
dec.sce <- modelGeneVar(sim)
rowData(sim)$biological.var <- dec.sce$bio

hvg <- (rownames(sim)[order(rowData(sim)$biological.var, decreasing = TRUE)])[1:500]

# add ALK to genes included in the analysis - see literature.

ensembl_ALK <-  rownames(sim)[rowData(sim)$gene_name == "ALK"]
hvg <- c(hvg,ensembl_ALK)
sim <- sim[hvg,]

logcounts = as.data.frame(as.matrix(logcounts(sim)))
counts = as.data.frame(as.matrix(counts(sim)))
cells = as.data.frame(colData(sim))
genes = as.data.frame(rowData(sim))
meta = metadata(sim)
groups = as.numeric(as.factor(cells$celltype))

n = ncol(sim)
m = nrow(sim)

X = model.matrix(~ 1, data = cells)
Z = matrix(1, nrow = m, ncol = 1)
Y = matrix(NA, nrow = n, ncol = m)
Y[] = t(counts)


family = poisson()
method = "bsgd"
control.init = list(method = "ols", type = "link")
control.alg = list(maxiter = 1000, size = c(100,100), frequency = 250)

gmf.fit.list = list()
ncomp <- c(1:10, 15, 20, 30, 40, 50)
for (i in 1:length(ncomp)) {
  cat(" Rank =", ncomp[i], "\n")
  # Fit the model
  fit = sgdGMF::sgdgmf.fit(Y, X, Z, ncomp = ncomp[i], family = family,
                           method = method, control.init = control.init, 
                           control.alg = control.alg)

  # Store the estimated model
  gmf.fit.list[[i]] = fit
}

saveRDS(object = gmf.fit.list, 
        file = paste0("Output_models/sgdGMF-B-SGD-fit-list-2clusters-500hvg.RDS"))
  
  
```


